config/routes.rb
Rails.application.routes.draw do
  root to: 'quiz_creation#index'
  devise_for :quiz_users, controllers: { registrations: "quiz_users/registrations", confirmations: "quiz_users/confirmations", sessions:"quiz_users/sessions" }

  resources :quiz_creation do
    collection do
      get :tutorials
      get :rejected_quizzes
      get :approved_quizzes
      get :submitted_quizzes
      get :unfinished_quizzes
    end
  end
  devise_scope :quiz_user do
    match 'login'            => 'quiz_users/sessions#create',         :via => :post
    match 'signup'           => 'quiz_users/registrations#create',    :via => :post
  end
  resources :courses
  resources :labels

  resources :quizzes do
    member do
      get :approve
      get :reject
      get :new_verison
      get :submit_for_approval
      get :study_guide
    end
    collection do
      get :quiz_results
    end
    resources :questions, :except => [:index] do
      member do
        put :change_order
      end
    end
  end

  get '/quiz_user_account', to: 'quiz_creation#quiz_user_account'
  post '/settings', to: 'quiz_creation#settings'
  post '/check_email', to: 'quiz_creation#check_email'
  post '/set_comment', to: 'quizzes#set_comment'
  post '/set_question_comment', to: 'questions#set_question_comment'
  post '/switch_alerts', to: 'quiz_creation#switch_alerts'
  get '/messages', to: 'quiz_creation#messages'

  

  post '/set_sample_question', to: 'quiz_creation#set_sample_question'
  match '*path' => redirect('/'), via: :get
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	accepts_nested_attributes_for :answers, allow_destroy: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_quiz_user!
  
  def set_question_comment
    data_params = {}
    data_params[:quiz_user_id] = params[:quiz_user_id]
    data_params[:user_type] = 'quiz_user'
    data_params[:id] = params[:id]
    data_params[:quiz_id] = params[:quiz_id]
    data_params[:chat_text] = params[:chat_text]
    res_json = make_request("api/v1/set_question_comment",data_params,"POST")
    if res_json['success']
      @quiz = res_json['quiz']
      @question = res_json['question']
      @chats = @question['comments']
      respond_to do |format|
        format.js { render :show }
      end
    else
      redirect_to :back
    end
  end

  def new
    data_params={}
    res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}",data_params,"GET")
    @quiz = res_json["quiz"]
    @labels = res_json['labels']
    @question = Question.new
    @question.answers.build
  end

  def create
    error_msgs = []
    correct_count = 0
    wrong_count = 0
    no_attachments = true

    if params[:question][:text].blank?
      error_msgs.push("Question cannot be blank.\n")
      flash[:alert] = error_msgs
    end
    
    if params[:question][:study_guide_attachment].present?
      params[:question][:guide_filename] = params[:question][:study_guide_attachment].original_filename
    end

    params[:question][:answers_attributes].each do |(first_index, last_index)|
      if (last_index["text"].blank? && last_index["attachment"].blank?)
        params[:question][:answers_attributes].delete(first_index.to_s)
      else
        if last_index["correct"]=="1"
          correct_count = correct_count + 1
        else
          wrong_count = wrong_count + 1
        end

        if !last_index["attachment"].blank?
          no_attachments = false

          Utils::Utils.add_file_upload_with_keys!(
            params,
            [
              :question,
              :answers_attributes,
              first_index,
              "attachment"
            ]
          )
        end
      end
    end

    if params[:question][:answers_attributes].blank?
      error_msgs.push("You have to enter the answers.\n")
      flash[:alert] = error_msgs
      # redirect_to :back and return
    end

    if correct_count == 0
      error_msgs.push("You have to enter at least one correct answer.\n")
      flash[:alert] = error_msgs
      # redirect_to :back and return
    elsif wrong_count == 0
      error_msgs.push("You have to enter at least one incorrect answer.\n")
      flash[:alert] = error_msgs
      # redirect_to :back and return
    end

    if correct_count == 0 || wrong_count == 0 || params[:question][:answers_attributes].blank? || params[:question][:text].blank?
      data_params = {}
      res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}",data_params,"GET")
      @quiz = res_json["quiz"]
      @labels = res_json["labels"]
      @question = Question.new question_params
      # @question.answers.build
      flash[:alert] = error_msgs
      render :action => 'new' and return

      # redirect_to :back and return
    end

    Utils::Utils.add_file_upload!(params, :study_guide_attachment)
    Utils::Utils.add_file_upload!(params, :attachment)

    no_attachments = (no_attachments &&
                      params[:question][:study_guide_attachment].blank? &&
                      params[:question][:attachment].blank?)

    if no_attachments
      data_params={}
      data_params[:question] = params[:question]
      if params[:label_all].present?
        data_params['label_all[]'] = params[:label_all]
      end
      res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}/questions",data_params,"POST")
      if res_json['success']
        quiz_id = res_json['quiz']['id']
        question_id = res_json['question']['id']
        redirect_to quiz_question_path(quiz_id,question_id) and return
      else
        redirect_to :back
      end
    else
      @response = Utils::Utils.make_post_request_with_upload!(
        "api/v1/quizzes/#{params[:quiz_id]}/questions",
        {
          "question" => params[:question],
          "auth_token" => session[:auth_token],
          'label_all[]' => params[:label_all]
        }
      )

      if @response.code.to_i == 200
        res_json = JSON.parse(@response.body)
        quiz_id = res_json['quiz']['id']
        question_id = res_json['question']['id']
        redirect_to quiz_question_path(quiz_id,question_id) and return
      else
        b = @response.body
        flash[:alert] = "An Error Occured while adding question."
        return redirect_to :back
      end
    end
  end

  def show
    data_params={}
    res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}/questions/#{params[:id]}",data_params,"GET")
    if res_json['success']
      @quiz = res_json['quiz']
      @question = res_json['question']
      @qs = res_json['questions']
      @current_page = @question['question_number']
      @total_questions =  @qs.last['question_number']

      current_index = @qs.index {|h| h["question_number"] == @current_page }

      prev_index = 0
      prev_index = current_index -1 unless current_index == 0
      next_index = current_index + 1 
      prev_list = @qs[prev_index]

      next_list = @qs[next_index]

      if next_list.present?
        @next_url = "/quizzes/#{@quiz['id']}/questions/#{next_list['id']}"
      else
        @next_url = "javascript:void(0);"
      end

      if prev_list.present?
        @prev_url = "/quizzes/#{@quiz['id']}/questions/#{prev_list['id']}"
      else
        @prev_url = "javascript:void(0);"
      end
    else
      flash[:alert] = res_json["message"]
      redirect_to root_path
    end

  end

  def change_order
    @question.change_order params[:move].to_i
    redirect_to [@device, @quiz]
  end

  def edit
    data_params={}
    res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}/questions/#{params[:id]}/edit",data_params,"GET")

    if res_json['success']
      @quiz = res_json['quiz']
      @question = res_json['question']
      @question_labels = res_json["question_labels"]
      @labels = res_json["labels"]
      question = Question.find_by_id @question['id']
      params[:question] =  set_params_question(@question)

      if question.present?
        params[:question] = params[:question].except(:answers_attributes)
        question.update question_params
        question.answers.destroy_all
      else
        question = Question.create question_params
      end

      @question['answers'].each do |answer|
        question.answers.create(
          id: answer['id'],
          text: answer['text'],
          question_id: answer['question_id'],
          latex: answer['latex'],
          correct: answer['correct'],
          created_at: answer['created_at'],
          updated_at: answer['updated_at'],
          attachment_url: answer['attachment']['url']
        )
      end
      @question = question
    else
      flash[:alert] = res_json["message"]
      redirect_to root_path
    end

  end

  def update
    require 'mime/types'
    require 'rack'

    correct_count = 0
    wrong_count = 0
    empty_count = 0

    no_attachments = true

    if params[:question][:study_guide_attachment].present?
      params[:question][:guide_filename] = params[:question][:study_guide_attachment].original_filename
    end

    params[:question][:answers_attributes].each do |t|
      first_index = t.first
      last_index = t.last
      if (last_index["_destroy"] !="false" &&
          last_index["text"].blank? &&
          last_index["attachment"].blank?)
        params[:question][:answers_attributes].delete(first_index.to_s)
      else
        if last_index["_destroy"] == "false"
          empty_count = empty_count + 1
          if last_index["correct"]=="1" 
            correct_count = correct_count + 1
          else
            wrong_count = wrong_count + 1
          end

          if !last_index["attachment"].blank?
            no_attachments = false

            Utils::Utils.add_file_upload_with_keys!(
              params,
              [
                :question,
                :answers_attributes,
                first_index,
                "attachment"
              ]
            )
          end
        end
      end
    end

    if params[:question][:answers_attributes].blank? || empty_count == 0
      flash[:alert] = "You have to enter the answers"
      redirect_to :back and return
    end

    if correct_count == 0
      flash[:alert] = "You have to enter at least one correct answer"
      redirect_to :back and return
    elsif wrong_count == 0
      flash[:alert] = "You have to enter at least one incorrect answer"
      redirect_to :back and return
    end

    Utils::Utils.add_file_upload!(params, :study_guide_attachment)
    Utils::Utils.add_file_upload!(params, :attachment)

    no_attachments = (no_attachments &&
                      params[:question][:study_guide_attachment].blank? &&
                      params[:question][:attachment].blank?)
    if no_attachments
      data_params={}
      data_params[:question] = params[:question]
      if params[:label_all].present?
        data_params['label_all[]'] = params[:label_all]
      end
      res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}/questions/#{params[:id]}",data_params,"PUT")
      if res_json['success']
        quiz_id = res_json['quiz']['id']
        question_id = res_json['question']['id']
        redirect_to quiz_question_path(quiz_id,question_id)
        return
      else
        redirect_to :back
      end
    else
      @response = Utils::Utils.make_put_request_with_upload!(
        "api/v1/quizzes/#{params[:quiz_id]}/questions/#{params[:id]}",
        {
          "question" => params[:question],
          "auth_token" => session[:auth_token]
        }
      )

      if @response.code.to_i == 200
        res_json = JSON.parse(@response.body)
        quiz_id = res_json['quiz']['id']

app/views/questions/_chat_box.html.erb
<% prev_val = nil %>
<% op  = @chats.first['posted_by'] %>
<% @chats.each_with_index do |comment,index| %>
  <% if op == comment['posted_by'] %>
    <li class="left clearfix"><span class="chat-img pull-left">
      <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" /></span>
      <div class="chat-body clearfix">
        <div class="header">
          <strong class="primary-font"><%=comment['posted_by_email']%></strong> <small class="pull-right text-muted">
          <span class="glyphicon glyphicon-time"></span><%= time_ago_in_words(comment['created_at']) %></small>
        </div>
        <p><%=comment['text']%></p>
      </div>
    </li>
  <%else%>
    <li class="right clearfix"><span class="chat-img pull-right">
      <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" /></span>
      <div class="chat-body clearfix">
        <div class="header">
          <small class=" text-muted"><span class="glyphicon glyphicon-time"></span><%= time_ago_in_words(comment['created_at']) %></small>
          <strong class="pull-right primary-font"><%=comment['posted_by_email']%></strong>
        </div>
        <p><%=comment['text']%></p>
      </div>
    </li>
  <%end%>
  <% prev_val = comment['posted_by'] %>
<%end%>

app/views/questions/_form.html.erb
<%= nested_form_for @question, url: quiz_questions_path , html: {multipart:true, class: 'form-horizontal'} do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>Please fix following issues :</h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :text, "Question" %>
    </div>
    <div class="col-sm-4">
      <%= f.text_area :text, class: 'form-control', placeholder: "Max length 10,000 characters", maxlength: 10000 %>
    </div>
   <!--  <div class="col-sm-12">
      <div class="col-sm-4 col-sm-offset-2">
        <%= f.label :latex_text %>
        <%= f.check_box :latex %>
      </div>
    </div>
    <div class="col-sm-12">
      <div class="col-sm-2 control-label">
        <label>Question Attachment</label>
      </div>
      <div class="col-sm-4">
        <%=  file_field_tag "question[attachment]", class: 'form-control', placeholder: '.pdf,image/*',:accept => ".pdf,image/*" %>
      </div>
    </div> -->
  </div>

  <div class="col-sm-12 col-sm-offset-1">
    <p class='lead'>Answers</p>
  </div>

  <div id="answers">
    <%= f.fields_for :answers do |a| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= a.label :textm, "Answer" %>
        </div>
        <div class="col-sm-4">
          <%= a.text_area :text, class: 'form-control', placeholder: "Max length 10,000 characters", maxlength: 10000 %>
        </div>
        <span class="input-group-btn">
          <%= a.link_to_remove 'Remove answer', class: 'btn btn-danger' %>
        </span>
        <div class="col-sm-12">
          <div class="col-sm-offset-2 col-sm-2">
            <%= a.label :correct %>
            <%= a.check_box :correct %>
          </div>
          <!-- <div class="col-sm-4">
            <%= a.label :latex_text %>
            <%= a.check_box :latex %>
          </div> -->
        </div>

        <!-- <div class="col-sm-12 answer-file-attachment-input">
          <div class="col-sm-2 control-label">
            <label>Attachment</label>
          </div>
          <div class="col-sm-4">
            <%= a.file_field :attachment, class: 'form-control', placeholder: '.pdf,image/*',:accept => ".pdf,image/*" %>
          </div>
        </div> -->
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">
      <%= f.link_to_add 'Add Answer', :answers, :data => { :target => "#answers", :maximum => 4}, :class => 'btn btn-success'  %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Select Labels for the question</label>
    </div>
    <div class="col-sm-4">
      <select id="question_label_id" name="label_all[]" class="form-control select-label" multiple="multiple">
        <% labels = @labels %>
        <% labels.each do |label| %>
          <option value="<%= label['id'] %>"><%= label['name']%></option>
        <% end %>
      </select>
    </div>
  </div>




  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :hint, "Hint" %>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :hint, class: 'form-control' %>
    </div>
  </div>


  <!-- <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Comment Box for this Question</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_area :comment, class: 'form-control' %>
    </div>
  </div> -->

  <!-- <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Question Study Type :</label>
    </div>
    <div class="col-sm-4">
      <input type = "radio" class = "form-control guide-text" name="quiz_guide">Study Guide Text
      <br>
      <input type = "radio" class = "form-control guide-pdf" name="quiz_guide">Study Guide PDF
    </div>
  </div> -->


  <div class="form-group guide-field hidden">
    <div class="col-sm-2 control-label">
      <label>Question Study Guide</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_area :study_guide, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group pdf-field hidden">
    <div class="col-sm-2 control-label">
      <label>Question Study Guide PDF</label>
    </div>
    <div class="col-sm-4">
      <%=  file_field_tag "question[study_guide_attachment]", class: 'form-control', placeholder: '.pdf,image/*',:accept => ".pdf,image/*" %>
    </div>
  </div>

  <hr>
  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', cancel_link, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){

    $(".select-label").select2({
      placeholder: "Select Label"
    });

    $(".guide-text").click(function(){

      $(".guide-field").removeClass("hidden")
      $(".pdf-field").addClass("hidden");
    });

    $(".guide-pdf").click(function(){
      $(".pdf-field").removeClass("hidden");
      $(".guide-field").addClass("hidden")
      
    });

  });

</script>

app/views/questions/edit.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>Edit '<%= @question['text'] %>'</h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'edit_form', :cancel_link => quiz_path(@quiz['id']) %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="col-sm-12">
  <div class="col-sm-11">
    <h1>Question for '<%= @quiz.name %>'</h1>
  </div>
  <div class="col-sm-1">
    <h2>
      <%= link_to 'New Question', new_device_quiz_question_path, :class => 'btn btn-primary' %>
    </h2>
  </div>
</div>

app/views/questions/new.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>New Question for '<%= @quiz['name'] %>'</h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'form', :cancel_link => quiz_creation_index_path %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<%# breadcrumb :answers, @quiz, @question %>
<%if @quiz['quiz_status'].try(:downcase) == 'pending' || @quiz['quiz_status'].try(:downcase) == 'rejected' %>
  <% quiz_link_text = "Submitted Quizzes" %>
  <% quiz_link = "/quiz_creation/submitted_quizzes" %>
<% elsif @quiz['quiz_status'].try(:downcase) == 'approved' %>
  <% quiz_link_text = "Approved Quizzes" %>
  <% quiz_link = "/quiz_creation/approved_quizzes" %>
<% elsif @quiz['quiz_status'].try(:downcase) == 'incomplete' %>
  <% quiz_link_text = "Quizzes" %>
  <% quiz_link = "/quiz_creation/unfinished_quizzes" %>
<%else%>
<% quiz_link_text = "Quizzes" %>
<% quiz_link = "/quiz_creation/unfinished_quizzes" %>
<%end%>


<%active_quiz = @quiz['name'].to_s.truncate(25) %>

<ol class="breadcrumb">
  <li>
    <a href="/">Home</a>
  </li>
  <li>
    <a href="<%=quiz_link%>"><%=quiz_link_text%></a>
  </li>
  <li>
    <a href="/quizzes/<%=@quiz['id']%>"><%=active_quiz%></a>
  </li>
  <li class="active">
    Question <%= @question['question_number'] %>
  </li>
</ol>

<div class="panel mb25">
  <div class="panel-heading">
    <div class="col-xs-12">
      <div class="row">
        <h1 class="col-md-10">
          <%= @quiz['name'] %>
        </h1>
        <div class="col-md-2 align-actions-with-heading">
            <%if @quiz['quiz_status']=="incomplete" %>
            <%= link_to 'Edit', edit_quiz_question_path(@quiz['id'], @question['id']), :class => 'btn btn-default' %>
            <%= link_to 'Add Question &plus;'.html_safe, new_quiz_question_path(@quiz['id']), class: 'btn btn-primary' %>
            <%end%>
  
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= @question['text'] %>
          </h3>
        </div>
        <h5>
          Hint: <%= @question['hint'] %>
        </h5>
        <div class="panel-body">
          <% @question['answers'].each do |answer| %>
            <% if answer['attachment']['url'].present? %>
              <%= link_to "Link", answer['attachment']['url'], :class => "btn btn-#{answer['correct'].present? ? 'success' : 'default'}"%>
            <% else %>
              <%= button_tag answer['text'], :type => :button, :class => "btn btn-#{answer['correct'].present? ? 'success' : 'default'}" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row text-center">
  <ul class="pagination">
    <% unless @current_page == 1 %>
      <li>
        <a href="<%=@prev_url%>" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    <%end%>
    <% @qs.each_with_index do |question,index| %>
      <% count = index + 1 %>
      <% if @current_page == count %>
        <li class="active"><%= link_to count, quiz_question_path(@quiz['id'], question['id']) %>
        </li>
      <%else%>
        <li><%= link_to count, quiz_question_path(@quiz['id'], question['id']) %></li>
      <%end%>
    <%end%>
    <% unless @current_page == @total_questions %>
      <li>
        <a href="<%=@next_url%>" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    <%end%>
  </ul>
</div>


<%if @question['study_guide'].present? %>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          View Study Guide
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%=@question['study_guide']%>
      </div>
    </div>
  </div>
</div>
<%end%>

<%if @question['study_guide_attachment_url'].present? %>
<div class="panel-group" id="accordion1" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          View Study Guide
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <iframe src= <%=@question['study_guide_attachment_url']%> width="600" height="780" style="border: none;"> </iframe>
      </div>
    </div>
  </div>
</div>
<%end%>




<!--Chat -->

<!-- <div class="container">
  <div class="row">
    <div class="col-md-5">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-comment"></span> Chat
        </div>
        
        <div class="panel-body panel-body-chat" id="chat-panel-question">
          <%if @question['comments'].blank? %>
            <p>No chat History</p>
          <%else%>
            <ul class="chat" id="chatBoxQuestion">
              <% @chats = @question['comments'] %>
              <%= render(partial: 'chat_box')%>
              
            </ul>
          <%end%>  
        </div>
          
      
        <div class="panel-footer">
          <div class="input-group">
            <input id="chat-input-question" type="text" class="form-control input-sm" placeholder="Type your message here..." />
            <span class="input-group-btn">
              <input type="hidden" id="quiz-user-id">
              <button class="btn btn-primary btn-sm" id="btn-chat-question">Send</button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>

</div> -->




<script type="text/javascript">
  $('.collapse').collapse();

  $(document).ready(function(){
    $('.sample-ques').click(function(){
      question_id = this.getAttribute('id');
      var apiURL = "/set_sample_question";

      $.ajax({
        url : apiURL,
        type: "POST",
        data :{ question_id: question_id },
        success: function(data, textStatus, jqXHR)
        {},
        error: function (jqXHR, textStatus, errorThrown)
        {}
      });
    });

    $('#btn-chat-question').click(function(){
      var quizID = "<%=@quiz['id']%>";

      var questionID = "<%=@question['id']%>";

      var userEmail = "<%=session[:quiz_user]['email']%>";
      var chatTextDiv = document.getElementById('chat-input-question');
      var chatText = document.getElementById('chat-input-question').value;
      var chatPanel = $("#chat-panel-question");
      var userId = "<%=session[:quiz_user]['id']%>";
      var userType = "quizuser";
      if (chatText)
      {
        $.ajax({
          url : '/set_question_comment',
          dataType: 'script',
          type: "POST",
          data :{ quiz_user_id: userId, user_type: userType, id: questionID, chat_text: chatText, quiz_id: quizID },
          success: function(data, textStatus, jqXHR)
          {},
          error: function (jqXHR, textStatus, errorThrown)
          {}
        });

        var text = chatText;
        var chat =  '<li class="right clearfix"><span class="chat-img pull-right"><img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" /></span><div class="chat-body clearfix"><div class="header"><small class=" text-muted"><span class="glyphicon glyphicon-time"></span>Just Now</small><strong class="pull-right primary-font">' + userEmail  +'</strong></div><p>'+ text +'</p></div></li>'


        var chat2 =  '<ul class="chat" id="chatBoxQuestion"><li class="right clearfix"><span class="chat-img pull-right"><img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" /></span><div class="chat-body clearfix"><div class="header"><small class=" text-muted"><span class="glyphicon glyphicon-time"></span>Just Now</small><strong class="pull-right primary-font">' + userEmail  +'</strong></div><p>'+ text +'</p></div></li></ul>'
        var chatBox =document.getElementById('chatBoxQuestion');
        
        if(chatBox){
          chatBox.innerHTML += chat;  
        }
        else{
          chatPanel.html("");
          chatPanel.html(chat2);
        }
        $("#chat-input-question").val("");
      }
    });
  });
</script>

app/views/questions/show.js.erb
$("#chatBoxQuestion").empty();
$("#chatBoxQuestion").html("<%= escape_javascript(render(partial: 'quizzes/chat_box', :locals => {:@chats => @chats})) %>");