config/routes.rb
Rails.application.routes.draw do
  root to: 'quiz_creation#index'
  devise_for :quiz_users, controllers: { registrations: "quiz_users/registrations", confirmations: "quiz_users/confirmations", sessions:"quiz_users/sessions" }

  resources :quiz_creation do
    collection do
      get :tutorials
      get :rejected_quizzes
      get :approved_quizzes
      get :submitted_quizzes
      get :unfinished_quizzes
    end
  end
  devise_scope :quiz_user do
    match 'login'            => 'quiz_users/sessions#create',         :via => :post
    match 'signup'           => 'quiz_users/registrations#create',    :via => :post
  end
  resources :courses
  resources :labels

  resources :quizzes do
    member do
      get :approve
      get :reject
      get :new_verison
      get :submit_for_approval
      get :study_guide
    end
    collection do
      get :quiz_results
    end
    resources :questions, :except => [:index] do
      member do
        put :change_order
      end
    end
  end

  get '/quiz_user_account', to: 'quiz_creation#quiz_user_account'
  post '/settings', to: 'quiz_creation#settings'
  post '/check_email', to: 'quiz_creation#check_email'
  post '/set_comment', to: 'quizzes#set_comment'
  post '/set_question_comment', to: 'questions#set_question_comment'
  post '/switch_alerts', to: 'quiz_creation#switch_alerts'
  get '/messages', to: 'quiz_creation#messages'

  

  post '/set_sample_question', to: 'quiz_creation#set_sample_question'
  match '*path' => redirect('/'), via: :get
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  before_action :authenticate_quiz_user!, :except => [:update_row_order]

  def quiz_results
    
    data_params={}
    res_json = make_request("/api/v1/quizzes/quiz_results",data_params,"GET")
    if res_json['success']
      @quiz_results = res_json["quiz_results"]
    else
      flash[:alert] = "An error occured. Can't display quiz results"
      redirect_to root_path
    end
  end

  def set_comment
    data_params = {}
    data_params[:quiz_user_id] = params[:quiz_user_id]
    data_params[:user_type] = 'quiz_user'
    data_params[:id] = params[:id]
    data_params[:chat_text] = params[:chat_text]
    res_json = make_request("api/v1/set_comment",data_params,"POST")
    if res_json['success']
      @quiz = res_json['quiz']
      @chats = @quiz['comments']
      respond_to do |format|
        format.js { render :show }
      end
    else
      redirect_to :back
    end
  end

  def new_verison
    data_params = {}
    res_json = make_request("api/v1/quizzes/#{params[:id]}/new_verison",data_params,"GET")
    if res_json['success']
      @quiz_revise = res_json['quiz_revise']
      redirect_to edit_quiz_path(@quiz_revise['id'])
    else
      redirect_to :back
    end 
  end

  def edit
    data_params={}
    res_json = make_request("api/v1/quizzes/#{params[:id]}/edit",data_params,"GET")
    
    if res_json['success']
      @quiz = res_json["quiz"]
      @grades = res_json["grades"]
    else
      flash[:alert] = res_json["message"]
      redirect_to root_path
    end
  end

  def study_guide
    if params[:study_text] || params[:study_comment].present?
      data_params = {}
      data_params[:study_text] = params[:study_text]
      data_params[:study_comment] = params[:study_comment]
      res_json = make_request("api/v1/quizzes/#{params[:id]}/study_guide",data_params,"GET")
      if res_json['success']
        @quiz = res_json['quiz']
        flash[:notice]="Study Guide Save"
        redirect_to quiz_path(@quiz['id'])
      else
        redirect_to :back
      end
    else
      data_params={}
      res_json = make_request("api/v1/quizzes/#{params[:id]}",data_params,"GET")
      @quiz = res_json["quiz"]
      @grades = res_json["grades"]
    end
  end

  def submit_for_approval
    data_params = {}
    res_json = make_request("api/v1/quizzes/#{params[:id]}/submit_for_approval",data_params,"GET")
    if res_json['success']
      flash[:notice]="Quiz submitted for Admin Approval"
      @quiz = res_json['quiz']
      redirect_to quiz_path(@quiz['id'])
    else
      flash[:notice]="An Error Occured"
      redirect_to :back
    end
  end


  def index
    # @q = @device.quiz_selections.ransack(params[:q])
    # @quizzes = @q.result(distinct: true).includes(:quiz => :grade).joins(:quiz => :grade)
    @q = Quiz.all.ransack(params[:q])
    # @quizzes = @q.result(distinct: true).includes(:grade).joins(:grade)
    @quizzes = @q.result(distinct: true)
  end

  def all_quizzes
    @quizzes = QuizSelection.joins(:device).where('devices.user_id = ?', current_user.id)
      .includes(:device, :quiz => :grade).order('quiz_selections.created_at DESC')
  end

  def new
    data_params = {}
    res_json = make_request("api/v1/quizzes/get_grades",data_params,"GET")
    @quiz_new = res_json['grades']
    @courses = res_json['courses']

  end

  def create
    require 'mime/types'
    require 'rack'

    unless params[:quiz][:attachment].blank?
      upload = params[:quiz][:attachment].is_a?(String)
      filename = upload  ? params[:quiz][:attachment] : params[:quiz][:attachment].original_filename
      params[:quiz][:quiz_supplement_filename] = filename
      extension = filename.split('.').last
      tmp_file = "#{Rails.root}/tmp/uploaded.#{extension}"
      id = 0
      while File.exists?(tmp_file) do
        tmp_file = "#{Rails.root}/tmp/uploaded-#{id}.#{extension}"        
        id += 1
      end
      File.open(tmp_file, 'wb') do |f|
        if upload
          f.write  request.body.read
        else
          f.write params[:quiz][:attachment].read
        end
      end
      file = File.open(tmp_file)
      params[:quiz][:attachment] = Rack::Multipart::UploadedFile.new(file.path, mime_for_file(file))
      File.delete(file.path)
    end

    unless params[:quiz][:quiz_guide_attachment].blank?
      upload = params[:quiz][:quiz_guide_attachment].is_a?(String)
      filename = upload  ? params[:quiz][:quiz_guide_attachment] : params[:quiz][:quiz_guide_attachment].original_filename
      params[:quiz][:quiz_guide_attachment_filename] = filename
      extension = filename.split('.').last
      tmp_file = "#{Rails.root}/tmp/uploaded.#{extension}"
      id = 0
      while File.exists?(tmp_file) do
        tmp_file = "#{Rails.root}/tmp/uploaded-#{id}.#{extension}"
        id += 1
      end
      File.open(tmp_file, 'wb') do |f|
        if upload
          f.write  request.body.read
        else
          f.write params[:quiz][:quiz_guide_attachment].read
        end
      end
      file = File.open(tmp_file)
      params[:quiz][:quiz_guide_attachment] = Rack::Multipart::UploadedFile.new(file.path, mime_for_file(file))
      File.delete(file.path)
    end

    if params[:quiz][:attachment].blank? && params[:quiz][:quiz_guide_attachment].blank?

      data_params={}
      data_params[:quiz] = params[:quiz]

      if params[:grade_all].present?
        data_params['grade_all[]'] = params[:grade_all]
      end
      res_json = make_request('api/v1/quizzes',data_params,request.env["REQUEST_METHOD"])
      @quiz =  res_json['quiz']

    else
      tmp_grade_params = params[:grade_all]
      if Rails.env.production?
        url = "#{Rails.configuration.parent_portal_url}/" + 'api/v1/quizzes'
        uri = URI(url)

        res = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
          request = Net::HTTP::Post.new(uri.request_uri)

          request.body = Rack::Multipart::Generator.new(
            "quiz"                  => params[:quiz],
            "auth_token"             => session[:auth_token]
          ).dump
          request.content_type = "multipart/form-data, boundary=#{Rack::Multipart::MULTIPART_BOUNDARY}"
          @response = http.request(request)
        end


      else
        url = "http://localhost:5000/" + 'api/v1/quizzes'
        uri = URI(url)
        http    = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Post.new(uri.request_uri)
        request.body = Rack::Multipart::Generator.new(
          "quiz"                  => params[:quiz],
          "auth_token"             => session[:auth_token]
        ).dump
        request.content_type = "multipart/form-data, boundary=#{Rack::Multipart::MULTIPART_BOUNDARY}"
        @response = http.request(request)

      end

      if @response.code.to_i == 200
        res_json = JSON.parse(@response.body)
        @quiz = res_json['quiz']
        data_params = {}
        data_params[:quiz_id] = @quiz['id']
        data_params['grade_all[]'] = tmp_grade_params
        res_json = make_request("api/v1/quizzes/add_grades",data_params,"POST")
      else
        flash[:alert] = "An Error Occured while adding quiz."
        return redirect_to :back
      end
    end

    if @quiz.present?
      redirect_to new_quiz_question_path(@quiz['id'])
    else
      redirect_to new_quiz_path
    end
  end

  def update

    ###############################################
    require 'mime/types'
    require 'rack'
    
    unless params[:quiz][:attachment].blank?
      upload = params[:quiz][:attachment].is_a?(String)
      filename = upload  ? params[:quiz][:attachment] : params[:quiz][:attachment].original_filename
      params[:quiz][:quiz_supplement_filename] = filename
      extension = filename.split('.').last
      tmp_file = "#{Rails.root}/tmp/uploaded.#{extension}"
      id = 0
      while File.exists?(tmp_file) do
        tmp_file = "#{Rails.root}/tmp/uploaded-#{id}.#{extension}"        
        id += 1
      end
      File.open(tmp_file, 'wb') do |f|
        if upload
          f.write  request.body.read
        else
          f.write params[:quiz][:attachment].read
        end
      end
      file = File.open(tmp_file)
      params[:quiz][:attachment] = Rack::Multipart::UploadedFile.new(file.path, mime_for_file(file))
      File.delete(file.path)
    end

    unless params[:quiz][:quiz_guide_attachment].blank?
      upload = params[:quiz][:quiz_guide_attachment].is_a?(String)
      filename = upload  ? params[:quiz][:quiz_guide_attachment] : params[:quiz][:quiz_guide_attachment].original_filename
      extension = filename.split('.').last
      params[:quiz][:quiz_guide_attachment_filename] = filename
      tmp_file = "#{Rails.root}/tmp/uploaded.#{extension}"
      id = 0
      while File.exists?(tmp_file) do
        tmp_file = "#{Rails.root}/tmp/uploaded-#{id}.#{extension}"        
        id += 1
      end
      File.open(tmp_file, 'wb') do |f|
        if upload
          f.write  request.body.read
        else
          f.write params[:quiz][:quiz_guide_attachment].read
        end
      end
      file = File.open(tmp_file)
      params[:quiz][:quiz_guide_attachment] = Rack::Multipart::UploadedFile.new(file.path, mime_for_file(file))
      File.delete(file.path)
    end

    if params[:quiz][:attachment].blank? && params[:quiz][:quiz_guide_attachment].blank?

      data_params = {}
      data_params[:quiz] = params[:quiz]
      if params[:grade_all].present?
        data_params['grade_all[]'] = params[:grade_all]
      end
      res_json = make_request("api/v1/quizzes/#{params[:id]}",data_params,"PUT")
      if res_json['success']
        flash[:success] = "Quiz updated successfully."
        @quiz =  res_json['quiz']
      end

    else
      tmp_grade_params = params[:grade_all]
      if Rails.env.production?
        url = "#{Rails.configuration.parent_portal_url}/" + "api/v1/quizzes/#{params[:id]}"
        uri = URI(url)

app/views/quizzes/all_quizzes.html.erb
<% breadcrumb :all_quizzes %>
<div class="panel mb25">
  <div class="panel-heading broder">
    <div>
      <h1>All Quizzes of '<%= current_user.email %>'</h1>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover">
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Device</th>
            <th>Subject</th>
            <th>Standard</th>
            <th>created_at</th>
          </tr>
          <% @quizzes.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection.quiz.name %></td>
              <td><%= quiz_selection.device %></td>
              <td><%= quiz_selection.quiz.subject %></td>
              <td><%= quiz_selection.quiz.grades.map(&:name).join(",") %></td>
              <td><%= quiz_selection.created_at.to_formatted_s :long_ordinal %></td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

app/views/quizzes/index.html.erb
<% breadcrumb :quizzes, @device %>
<div class="panel mb25">
  <div class="panel-body">
    <div class="col-lg-12">
      <div class="row">
        <%= search_form_for @q, :url => quizzes_path do |f| %>
          <div class="col-lg-6">
            <%= f.search_field :name_cont, :class => 'form-control', :placeholder => 'Search quizzes by name...' %>
          </div>
          <div class="col-lg-5">
            <%= f.select :grade_id_eq, options_from_collection_for_select(Grade.all.order(:priority), :id, :name, @q.grade_id_eq),
              {:include_blank => 'All Standards'}, :class => 'form-control' %>
          </div>
          <div class="col-lg-1">
            <%= f.submit 'Search', :class => 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>Quizzes</h1>
    </div>
    <div class="col-sm-5">
      <h2 class="pull-right">
        <%= link_to('Clear Filters', quizzes_path(:q => {:s => 'priority ASC'}),
          :class => 'btn btn-danger') unless params[:q].try(:[], :s).try :include?, 'priority' %>
        
        <%= link_to 'New Quiz', new_quiz_path, :class => 'btn btn-primary' %>
      </h2>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_id">
          <tr>
            <th>#</th>
            <th><%= sort_link(@q, :name, "Name") %></th>
            <!-- <th>Status</th> -->
            <th><%= sort_link(@q, :subject) %></th>
            <th><%= sort_link(@q, :grade_priority, 'Standard') %></th>
            <th>Priority</th>
            <th><%= sort_link(@q, :created_at) %></th>
            <th>Actions</th>
          </tr>
          <% @quizzes.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection.name %></td>
              <!-- <td><%#= humanized_status quiz_selection.quiz %></td> -->
              <td><%= quiz_selection.subject %></td>
              <td><%= quiz_selection.grades.map(&:name).join(",") %></td>
              <td>
                <% condition = params[:q].try(:[], :s).try :include?, 'priority' %>
                
              </td>
              <td><%= quiz_selection.created_at.to_formatted_s :long_ordinal %></td>
              <td>
                <%= link_to 'View Questions',quiz_path(quiz_selection), :class => 'btn btn-default' %>
                <%= link_to 'Edit', [:edit, quiz_selection], :class => 'btn btn-warning' %>
                <%= link_to [quiz_selection], :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-danger' do %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

app/views/quizzes/new.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>Add New Quiz</h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'form', :cancel_link => quiz_creation_index_path %>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/show.html.erb
<%if @quiz['quiz_status'].try(:downcase) == 'pending' || @quiz['quiz_status'].try(:downcase) == 'rejected' %>
  <% quiz_link_text = "Submitted Quizzes" %>
  <% quiz_link = "/quiz_creation/submitted_quizzes" %>
<% elsif @quiz['quiz_status'].try(:downcase) == 'approved' %>
  <% quiz_link_text = "Approved Quizzes" %>
  <% quiz_link = "/quiz_creation/approved_quizzes" %>
<% elsif @quiz['quiz_status'].try(:downcase) == 'incomplete' %>
  <% quiz_link_text = "Quizzes" %>
  <% quiz_link = "/quiz_creation/unfinished_quizzes" %>
<%else%>
<% quiz_link_text = "Submitted Quizzes" %>
<% quiz_link = "/quiz_creation/unfinished_quizzes" %>
<%end%>
<%active_quiz = @quiz['name'].to_s.truncate(25) %>

<ol class="breadcrumb">
  <li>
    <a href="/">Home</a>
  </li>
  <li>
    <a href="<%=quiz_link%>"><%=quiz_link_text%></a>
  </li>
  <li class="active">
    <%= active_quiz %>
  </li>
</ol>

<div class="panel mb25">
  <div class="panel-body" id="uniq-panel">
    <div class="col-md-12">
      <div class="row">
        <h2 class="col-md-8">
          <%= @quiz['name'] %>
        </h2>
        <div style="font-weight:800;">
          <%= link_to 'Edit', edit_quiz_path(@quiz['id']) %>
        </div>
        <!-- <div class="col-md-4 align-actions-with-heading">
          <li class="dropdown user-info">
          <a href="#" class="dropdown-toggle  admin-action" data-toggle="dropdown">
            Actions<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <%if @quiz['quiz_status'].try(:downcase)=="incomplete" %>
            <li><%= link_to 'Edit', edit_quiz_path(@quiz['id']) %></li>
            <li><%= link_to 'Add Question &plus;'.html_safe, new_quiz_question_path(@quiz['id']) %>
            </li>
            <%end%>
            
          </ul>
        </li>
        </div> -->
      </div>
    </div>
    <div class="col-md-12">
      <div>
        <b>Difficulty Level:</b>
        <%= @quiz['grades'].join(",")  %>
      </div>

      <div>
        <b>Passing Percentage:</b>
        <%= @quiz['passing_percentage'] %>
      </div>

      <div>
        <b>Topic:</b>
        <%= @quiz['topic'] %>
      </div>

      <div>
        <b>Description:</b>
        <%= @quiz['description'].to_s %>
      </div>
    </div>
  </div>
</div>
<div class="panel mb25">
  <div class="panel-body">
    <h4>Questions</h4>
    <div style="float: right;margin-top: -20px;font-weight:800;">
      <%= link_to 'Add Question'.html_safe, new_quiz_question_path(@quiz['id']) %>
    </div>
    <br>
    <table class="table table-responsive table-hover">
      <tr>
        <th>#</th>
        <th>Text</th>
        <th>Priority</th>
        <th>Created At</th>
        <th>Details</th>
      </tr>
      <% @quiz['questions'].each_with_index do |question, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= question['text'] %></td>
          <% if @quiz.present? %>
            <td>
              
            </td>
          <% end %>
          <td><%= question['created_at'].to_date.to_formatted_s :long_ordinal %></td>
          <td>
            <%= link_to 'Details', quiz_question_path(@quiz['id'], question['id']), :class => 'btn btn-default'  %>
              <%if @quiz['quiz_status'].try(:downcase)=="incomplete" %>
              <%= link_to 'Edit', edit_quiz_question_path(@quiz['id'], question['id']), :class => 'btn btn-warning' %>
              <%= link_to "/quizzes/#{@quiz['id']}/questions/#{question['id']}", :method => :delete, :data => {:confirm => 'Are you sure you want to delete the question?'}, :class => 'btn btn-danger' do %>
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
              <% end %>
              <%end%>
            
          </td>
         
          <<!-- td><%= radio_button_tag 'sample_question', "", (question['sample'].present?), class: "sample-ques", id: question['id'] %></td> -->
          
        </tr>
      <% end %>
    </table>
  </div>
</div>
  <!-- </div> -->

<%if @quiz['quiz_guide'].present? %>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          View Study Guide
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%=@quiz['quiz_guide']%>
      </div>
    </div>
  </div>
</div>
<%end%>

<%if @quiz['supplement_text'].present? %>
<div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          View Quiz Study Supplement
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <%=@quiz['supplement_text']%>
      </div>
    </div>
  </div>
</div>
<%end%>

<%if @quiz['attachment_url'].present? %>
<div class="panel-group" id="accordion3" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion3" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          View Quiz Supplement PDF
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <iframe src= <%=@quiz['attachment_url']%> width="600" height="780" style="border: none;"> </iframe>
      </div>
    </div>
  </div>
</div>
<%end%>

<%if @quiz['quiz_guide_attachment_url'].present? %>
<div class="panel-group" id="accordion4" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion4" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
          View Quiz Guide PDF
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <iframe src= <%=@quiz['quiz_guide_attachment_url']%> width="600" height="780" style="border: none;"> </iframe>
      </div>
    </div>
  </div>
</div>
<%end%>


<!-- <div class="container" id="chat-quiz">
  <div class="row">
    <div class="col-md-5">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-comment"></span> Chat
        </div>
        
        <div class="panel-body panel-body-chat" id="chat-panel">
          <%if @quiz['comments'].blank? %>
            <p>No chat History</p>
          <%else%>
            <ul class="chat" id="chatBox">
              <% @chats = @quiz['comments'] %>
              <%= render(partial: 'chat_box')%>
              
            </ul>
          <%end%>  
        </div>
          
      
        <div class="panel-footer">
          <div class="input-group">
            <input id="chat-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
            <span class="input-group-btn">
              <input type="hidden" id="quiz-user-id">
              <button class="btn btn-primary btn-sm" id="btn-chat">Send</button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>

</div> -->




<script type="text/javascript">
  $('.collapse').collapse()
  $(document).ready(function(){
    $('.sample-ques').click(function(){
      question_id = this.getAttribute('id');
      var apiURL = "/set_sample_question";

      $.ajax({
        url : apiURL,
        type: "POST",
        data :{ question_id: question_id },
        success: function(data, textStatus, jqXHR)
        {},
        error: function (jqXHR, textStatus, errorThrown)
        {}
      });
    });

    $('#btn-chat').click(function(){
      var quizID = "<%=@quiz['id']%>";
      var userEmail = "<%=session[:quiz_user]['email']%>";
      var chatTextDiv = document.getElementById('chat-input');
      var chatText = document.getElementById('chat-input').value;
      var chatPanel = $("#chat-panel");
      var userId = "<%=session[:quiz_user]['id']%>";
      var userType = "quizuser";
      if (chatText)
      {
        $.ajax({
          url : '/set_comment',
          dataType: 'script',
          type: "POST",
          data :{ quiz_user_id: userId, user_type: userType, id: quizID, chat_text: chatText },
          success: function(data, textStatus, jqXHR)
          {},
          error: function (jqXHR, textStatus, errorThrown)
          {}
        });

        var text = chatText;
        var chat =  '<li class="right clearfix"><span class="chat-img pull-right"><img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" /></span><div class="chat-body clearfix"><div class="header"><small class=" text-muted"><span class="glyphicon glyphicon-time"></span>Just Now</small><strong class="pull-right primary-font">' + userEmail  +'</strong></div><p>'+ text +'</p></div></li>'


        var chat2 =  '<ul class="chat" id="chatBox"><li class="right clearfix"><span class="chat-img pull-right"><img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" /></span><div class="chat-body clearfix"><div class="header"><small class=" text-muted"><span class="glyphicon glyphicon-time"></span>Just Now</small><strong class="pull-right primary-font">' + userEmail  +'</strong></div><p>'+ text +'</p></div></li></ul>'
        var chatBox =document.getElementById('chatBox');
        
        if(chatBox){
          chatBox.innerHTML += chat;  
        }
        else{
          chatPanel.html("");
          chatPanel.html(chat2);
        }
        $("#chat-input").val("");
      }
    });
  });
</script>

app/views/quizzes/show.js.erb
$("#chatBox").empty();
$("#chatBox").html("<%= escape_javascript(render(partial: 'quizzes/chat_box', :locals => {:@chats => @chats})) %>");

app/views/quizzes/study_guide.html.erb
<%= form_tag(study_guide_quiz_path, {:method => "get",:class => 'form-horizontal bordered-group'}) do %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Text for Study Guide</label>
    </div>
    <div class="col-sm-4">
      <input type="textarea" name="study_text" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Comment Box for Study Guide</label>
    </div>
    <div class="col-sm-4">
      <input type="textarea" name="study_comment" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">
      <input type="submit" value="Save Study Guide" class="btn btn-primary">
      <%= link_to 'Return to Quiz Overview', quiz_path(@quiz['id']), :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>