config/routes.rb
Rails.application.routes.draw do
  root to: 'quiz_creation#index'
  devise_for :quiz_users, controllers: { registrations: "quiz_users/registrations", confirmations: "quiz_users/confirmations", sessions:"quiz_users/sessions" }

  resources :quiz_creation do
    collection do
      get :tutorials
      get :rejected_quizzes
      get :approved_quizzes
      get :submitted_quizzes
      get :unfinished_quizzes
    end
  end
  devise_scope :quiz_user do
    match 'login'            => 'quiz_users/sessions#create',         :via => :post
    match 'signup'           => 'quiz_users/registrations#create',    :via => :post
  end
  resources :courses
  resources :labels

  resources :quizzes do
    member do
      get :approve
      get :reject
      get :new_verison
      get :submit_for_approval
      get :study_guide
    end
    collection do
      get :quiz_results
    end
    resources :questions, :except => [:index] do
      member do
        put :change_order
      end
    end
  end

  get '/quiz_user_account', to: 'quiz_creation#quiz_user_account'
  post '/settings', to: 'quiz_creation#settings'
  post '/check_email', to: 'quiz_creation#check_email'
  post '/set_comment', to: 'quizzes#set_comment'
  post '/set_question_comment', to: 'questions#set_question_comment'
  post '/switch_alerts', to: 'quiz_creation#switch_alerts'
  get '/messages', to: 'quiz_creation#messages'

  

  post '/set_sample_question', to: 'quiz_creation#set_sample_question'
  match '*path' => redirect('/'), via: :get
end

app/controllers/quiz_creation_controller.rb
class QuizCreationController < ApplicationController
	before_action :authenticate_quiz_user!, except: [:check_email]

  def messages
    data_params = {}
    
    if params[:quiz_id].present? && params[:question_id].present?
      res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}/questions/#{params[:question_id]}",data_params,"GET")
      @quiz = res_json['quiz']
      @question = res_json['question']
      @questions = res_json['questions']
    

    elsif params[:quiz_id].present?
      res_json = make_request("api/v1/quizzes/#{params[:quiz_id]}",data_params,"GET")
      if res_json['success']
        @quiz = res_json["quiz"]
        @grades = res_json["grades"]
        @questions = res_json["questions"]
        @question = @questions.first if @questions.present?
      else
        @quiz = nil
        @grades = nil
        @questions = nil
        @question = nil
      end
    else
      res_json = make_request("api/v1/quiz_messages",data_params,"GET")
      @quiz_results = res_json["quizzes"]
      @quiz_results ||=[]  
    end

    respond_to do |format|
      format.html do
      end
      format.js { render :msg_queue }
    end
    
  end
  
  def switch_alerts
    data_params = {}
    data_params[:switch_val] = params[:switch_val]
    res_json = make_request("api/v1/set_switch_val",data_params,"POST")
    return render json: true
  end

  def set_sample_question
    data_params = {}
    data_params[:question_id] = params[:question_id]
    res_json = make_request("api/v1/set_sample_question",data_params,"POST")
    return render json: true
  end


  def check_email
    data_params = {}
    data_params[:quiz_user] = params[:quiz_user]
    res_json = make_request('check_quiz_user_email',data_params,"POST")
    result = res_json["success"]
    return render :json => result
  end  
  
  def index
    data_params={}
    res_json = make_request('api/v1/quiz_creation',data_params,"GET")
    @quiz_results = res_json["quizzes"]
    @quiz_results ||=[]
  end

  def new
  end

  def edit
  end

  def update
  end
  
  def rejected_quizzes
    data_params={}
    res_json = make_request('api/v1/quiz_creation/rejected_quizzes',data_params,"GET")
    @quiz_results = res_json["rejected_quizzes"]
  end

  def approved_quizzes
    data_params={}
    data_params[:q]=params[:q]
    res_json = make_request('api/v1/quiz_creation/approved_quizzes',data_params,"GET")
    @grades = res_json["grades"]
    @quiz_results = res_json["approved_quizzes"]
  end

  def unfinished_quizzes
    data_params={}
    res_json = make_request('api/v1/quiz_creation/unfinished_quizzes',data_params,"GET")
    @quiz_results = res_json["unfinished_quizzes"]
  end

  def submitted_quizzes
    data_params={}
    res_json = make_request('api/v1/quiz_creation/submitted_quizzes',data_params,"GET")
    @quiz_results = res_json["submitted_quizzes"]
  end

  def tutorials
  end

  def quiz_user_account
    data_params = {}
    res_json = make_request('api/v1/user_info',data_params,"GET")
    @quiz_user = res_json["quiz_user"]
  end

  def settings
    data_params={}
    data_params[:quiz_user] = params[:quiz_user]
    res_json = make_request('api/v1/users/update_password',data_params,"POST")
    if res_json["success"]
      flash[:notice] = 'Password changed successfully'
      redirect_to quiz_creation_index_path
    else
      flash[:notice] = res_json['message']
      redirect_to :back
    end
  end

end

app/views/quiz_creation/_messages_form.html.erb
<%= form_tag(quizzes_path, {multipart: true, :class => 'form-horizontal bordered-group quiz-new-form'}) do %>

  

  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Quizzes</label>
    </div>
    <div class="col-sm-4">
      <% array = Array.new %>
      <% array = ["SAT Reading","SAT Math","SAT Writing and Language","ACT Math","ACT Reading", "ACT English", "ACT Science","Not Applicable"] %>
      <select class="form-control quiz-msg" id="quiz_test_prep" name="quiz[test_prep]">
        <% preps = array %>
        <% @quiz_results.each do |quiz| %>
          <option value="<%= quiz['id'] %>"><%= quiz['name']%></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">

    </div>
  </div>
<% end %>


<script type="text/javascript">
$(document).ready(function() {

  $('.quiz-msg').on('change', function() {
    console.log("TESTTTTTTTTTTTTTTTTTTTTTT");
    val = $(this).find("option:selected").val();
    console.log(val);
    $.ajax({
      type: 'GET',
      url: '/messages',
      dataType: 'script',
      data: {
        quiz_id: val
      }
    });
  });
  
});
</script>

app/views/quiz_creation/_questions_list.html.erb
<%= form_tag(quizzes_path, {multipart: true, :class => 'form-horizontal bordered-group quiz-new-form'}) do %>

  

  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Questions</label>
    </div>
    <div class="col-sm-4">
      <select class="form-control ques-msg">
        <%if @question.present? %>
          <option value="<%= @question['id'] %>"><%= @question['text']%></option>
        <%end%>
          <%if @questions.present? && @questions.count > 1%>
            <% @questions.each do |question| %>
              <%if question['id'] != @question['id'] %>
                <option value="<%= question['id'] %>"><%= question['text']%></option>
              <%end%>
            <% end %>
          <%end%>
      </select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">

    </div>
  </div>
<% end %>


<script type="text/javascript">
$(document).ready(function() {


  $('.ques-msg').on('change', function() {
    console.log("TESTTTTTTTTTTTTTTTTTTTTTT");
    var quizID = "<%=@quiz['id']%>";
    val = $(this).find("option:selected").val();
    console.log(val);
    $.ajax({
      type: 'GET',
      url: '/messages',
      dataType: 'script',
      data: {
        quiz_id: quizID,
        question_id: val
      }
    });

  });

  
});
</script>

app/views/quiz_creation/approved_quizzes.html.erb
<div class="panel mb25">
  <div class="panel-body">
    <div class="col-lg-12">
      <div class="row">
        
        <%= form_tag(approved_quizzes_quiz_creation_index_path, method:'get') do |f| %>
          <div class="col-lg-6">
            <%= search_field_tag 'q[name]','',class: 'form-control', placeholder: 'Search quizzes by name...'%>
          </div>
          <div class="col-lg-5">
            <select id="q_grade_id_eq" name="q[grade_id_eq]" class="form-control">
              <% grades = @grades %>
              <option value="all">All Standards</option>
              <% grades.each do |grade| %>
                <option value="<%= grade['id'] %>"><%= grade['name']%></option>
              <% end %>
            </select>
          </div>
          <div class="col-lg-1">
            <%= submit_tag("Search", :class=>"btn btn-default", :name=>"commit") %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>



<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>Approved Quiz Page</h1>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_unfinished">
          <tr>
            <th>#</th>
            <th>Quiz Name</th>
            <th>Subject</th>
            <th>Topic</th>
            <th>Test Prep</th>
            <th>Grade</th>
            <th>Description</th>
            <th>Sample Question</th>
          </tr>
          <% @quiz_results.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection['name'] %></td>
                <td><%= quiz_selection['subject'] %></td>
              <td><%=quiz_selection['topic'] %></td>
              <td><%=quiz_selection['test_prep'] %></td>
              <td><%= quiz_selection['grades'].join(",") %></td>
              <td><span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['description'] %>">Description</span></td>
              <td class=""><span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['first_question'].present? ? quiz_selection['first_question']['text'] : quiz_selection['default_question'] %>">Question</span></td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

<!-- popover -->
    <script>
    $(function () {
    $( "[data-toggle='popover']" ).popover( {container: 'body', html: 'true', trigger: 'hover'} );
     $('[data-toggle="tooltip"]').tooltip()
    })
    </script>

app/views/quiz_creation/edit.html.erb
<h1>QuizCreation#edit</h1>
<p>Find me in app/views/quiz_creation/edit.html.erb</p>

app/views/quiz_creation/index.html.erb
<div class="row ">
  <div class="col-md-9">
    <div class="quiz-cont fadeInUp">
    	<%if @quiz_results.blank? %>
    		<h1>No quizz added yet</h1>
    	<%else%>
    		<h1>Recently Added Quizzes</h1>
    	<%end%>
      <% @quiz_results.each do |quiz_result| %>
        <div class="quiz-row">
          <div class="top-bar clearfix">
            <span class="time"><%= quiz_result["created_at"].to_date.to_formatted_s(:minutes_and_seconds) %></span>
            <span class="date"><%= quiz_result["created_at"].to_date %></span>
          </div>
          <%= link_to quiz_path(quiz_result['id']), class: "quiz" do %>
            <span>Q.</span> <%= quiz_result['name'] %>
          <% end %>
          <!-- <div class="bottom-bar clearfix">
            <span class="device">Status: <%= quiz_result["quiz_status"] %></span>
          </div> -->
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-3 device-catTop">
    <div class="manage-devices">
      <h2>Select Options</h2>
      <ul>
       <li><%= link_to 'Create Quiz', new_quiz_path %></li>
        <li><%= link_to 'View Quizzes', unfinished_quizzes_quiz_creation_index_path %></li>
        <li><%= link_to 'Create Course', new_course_path  %></li>
        <li><%= link_to 'View Courses', courses_path  %></li>
        <li><%= link_to 'Create Labels', new_label_path  %></li>
        <li><%= link_to 'View Labels', labels_path  %></li>
        <li><%= link_to 'View Quiz Results', quiz_results_quizzes_path  %></li>
      </ul>
    </div>
  </div>

  
</div>

app/views/quiz_creation/messages.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>Quizzes</h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'messages_form' %>
      </div>
    </div>
  </div>
</div>

<div id="new-q-chat">
</div>




<div id="new-ques-chat">
</div>

app/views/quiz_creation/msg_queue.js.erb
<%if @quiz.present? %>
$("#new-q-chat").empty();
$("#new-q-chat").html("<%= escape_javascript(render(:partial => 'quiz_creation/quiz_msgs', :locals => {:@quizzes => @quizzes})) %>");
<%end%>

<%if @questions.present? && @question.present? %>
	$("#new-ques-chat").empty();
	$("#new-ques-chat").html("<%= escape_javascript(render(:partial => 'quiz_creation/ques_chat', :locals => {:@quiz => @quiz, :@questions => @questions, :@question => @question})) %>");
<%end%>

app/views/quiz_creation/new.html.erb
<h1>QuizCreation#new</h1>
<p>Find me in app/views/quiz_creation/new.html.erb</p>

app/views/quiz_creation/quiz_user_account.html.erb
<div class="col-md-6">
  <div class="account-management-cont">
    <h2>Account Management</h2>
    <h3>Change Password</h3>
    <%= form_for(:quiz_user, url: settings_path, html:{class: 'change-pwd-form'}) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>New Password:</label>
            <%= f.password_field :password, autocomplete: "off", class: 'form-control', id: 'quiz-ac-pwd' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>New Password Confirmation:</label>
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
           </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Current Password:</label>
            <%= f.password_field :current_password, autocomplete: "off", class: 'form-control', required: true, id: 'quiz-ac-pwd-1' %>
          </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label>Current Password Confirmation:</label>
              <%= f.password_field :current_password_confirmation, autocomplete: "off", class: 'form-control', required: true %>
            </div>
          </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <!-- <a href="" class=>Cancel</a> -->
            <%= link_to 'Cancel', :back, :class => "btn-block cancel-btn" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <!-- <a href="" class="btn-block update-btn">Update</a> -->
            <%= f.submit 'Update', :class => "btn-block update-btn", :id=>"unique-updt-btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="col-md-6">
  <div class="devices-cont">
    <h2>Email Alerts</h2>
    <div class="table-responsive">
    <p>Have Admin messages sent to my email. </p>
    <%= form_tag("/switch_alerts", remote: true, 'data-type' => :json, id: 'switch-alert-form') do %>
      <input type="hidden" class="hidden-switch-val" name="switch_val" >
      <%= check_box_tag :switch, @quiz_user['email_alert'], @quiz_user['email_alert'], :id => "sddss", :'data-toggle' => 'switch', :class => 'ct-blue device-switch' %>
    <%end%>
    <div class="table-responsive admin-contact">
      <p>Have a question? Send an email to <%= mail_to "Quiz.admin@cogli.com", "Quiz.admin@cogli.com", class: 'contact-email' %>, please Include your username. </p>
    </div>
  </div>
</div>





<script type="text/javascript">
$(document).ready(function(){

  $('.device-switch').on('change', function() {
    var enabler;
    value = $(this).parent().hasClass('switch-on');
    enabler = $(".hidden-switch-val");
    enabler.val(value);
    $("#switch-alert-form").submit();  
  });

  

  $(".change-pwd-form").validate({

    rules: {
      
      "quiz_user[current_password]": {
        required: true,
        minlength: 8
      },
      "quiz_user[password]": {
        required: true,
        minlength: 8
      },
      "quiz_user[password_confirmation]": {
        equalTo: "#quiz-ac-pwd"
      },
      "quiz_user[current_password_confirmation]": {
        equalTo: "#quiz-ac-pwd-1"
      }
    },
    messages: {
      "quiz_user[password]": {
        required: "Please provide a password",
        minlength: "Your password must be at least 8 characters long"
      },
      "quiz_user[password_confirmation]": {
       equalTo: "Password and Confirm Password does not match"
      },

      "quiz_user[current_password]": {
        required: "Please provide a password",
        minlength: "Your password must be at least 8 characters long"
      },
      "quiz_user[current_password_confirmation]": {
       equalTo: "Current Password and Confirm Current Password does not match"
      }

    },
    submitHandler: function(form) {
      form.submit();
    }
  });

});

</script>

app/views/quiz_creation/rejected_quizzes.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>Rejected Quiz Page</h1>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_unfinished">
          <tr>
            <th>#</th>
            <th>Username</th>
            <th>Quiz Name</th>
            <th>Subject</th>
            <th>Status</th>
            <th>Topic</th>
            <th>Test Prep</th>
            <th>Grade</th>
            <th>Description</th>
            <th>Sample Question</th>
            <th>Copy for Resubmission</th>
          </tr>
          <% @quiz_results.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection['quiz_user_name']%></td>
              <td><%= quiz_selection['name'] %></td>
              <td><%= quiz_selection['subject'] %></td>
              <td><%= quiz_selection['quiz_status'] %></td>
              <td><%= quiz_selection['topic'] %></td>
              <td><%= quiz_selection['test_prep'] %></td>
              <td><%= quiz_selection['grades'].join(",") %></td>
              <td class="">
                <span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['description'] %>">Description</span>
              </td>
               <td class=""><span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['first_question'].present? ? quiz_selection['first_question']['text'] : quiz_selection['default_question'] %>">Question</span></td>
               <td><%= link_to 'Copy for Resubmission', edit_quiz_path(quiz_selection['id']), :class => 'btn btn-default' %></td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

    <script>
    $(function () {
    $( "[data-toggle='popover']" ).popover( {container: 'body', html: 'true', trigger: 'hover'} );
     $('[data-toggle="tooltip"]').tooltip()
    })
    </script>

app/views/quiz_creation/submitted_quizzes.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>Submitted Quiz Page</h1>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_unfinished">
          <tr>
            <th>#</th>
            <th>Quiz Name</th>
            <th>Subject</th>
            <th>Grade</th>
            <th>Status</th>
            <th>Test Prep</th>
            <th>View Admin Comments</th>
            <th>Review Quiz</th>
            <th>Create New Version</th>
          </tr>
          <% @quiz_results.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection['name'] %></td>
              <td><%= quiz_selection['subject'] %></td>
              <td><%= quiz_selection['grade.name'] %></td>
              <td><%= quiz_selection['quiz_status'].try(:titleize) %></td>
              <td><%= quiz_selection['test_prep'] %></td>
              <td>
                <%= link_to 'View Admin Comments',quiz_path(quiz_selection['id']), :class => 'btn btn-default' %>
              </td>
              <td>
                <%= link_to 'Review Quiz',quiz_path(quiz_selection['id']), :class => 'btn btn-default' %>
              </td>
              <td>
                <%= link_to 'Create New Version',new_verison_quiz_path(quiz_selection['id']), :class => 'btn btn-default' %>
              </td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

app/views/quiz_creation/tutorials.html.erb
<div class="row ">
  <div class="col-md-6">
    <h1>10 Easy Animals to Draw</h1>
    <iframe width="420" height="345" src="https://www.youtube.com/embed/7SWvlUd2at8">
    </iframe>
  </div>

  <div class="col-md-6">
    <h1>How To Draw A Rainbow</h1>
    <iframe width="420" height="345" src="https://www.youtube.com/embed/Me_INPqx4WU">
    </iframe>
  </div>
  <div class="col-md-6">
    <h1>How To Draw A Rainbow</h1>
    <iframe width="420" height="345" src="https://www.youtube.com/embed/Me_INPqx4WU">
    </iframe>
  </div>
  <div class="col-md-6">
    <h1>How To Draw A Rainbow</h1>
    <iframe width="420" height="345" src="https://www.youtube.com/embed/Me_INPqx4WU">
    </iframe>
  </div>
</div>

app/views/quiz_creation/unfinished_quizzes.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>Unfinished Quiz Page</h1>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_unfinished">
          <tr>
            <th>#</th>
            <th>Quiz Name</th>
            <th>Difficulty Level</th>
            <th>Description</th>
            <th>Course</th>
            <th>View Quiz</th>
          </tr>
          <% @quiz_results.each_with_index do |quiz_selection, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= quiz_selection['name'] %></td>
              <td><%= quiz_selection['grades'].join(",") %></td>
              <td class="">
                <span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['description'] %>">Description</span>
              </td>


              <!-- <td class=""><span data-container="body" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="<%= quiz_selection['first_question'].present? ? quiz_selection['first_question']['text'] : quiz_selection['default_question'] %>">Question</span></td> -->
              <td><%=quiz_selection['course_name']%></td>
              <td>
                <%= link_to 'View Quiz',quiz_path(quiz_selection['id']), :class => 'btn btn-default' %>
              </td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

<!-- popover -->
    <script>
    $(function () {
    $( "[data-toggle='popover']" ).popover( {container: 'body', html: 'true', trigger: 'hover'} );
     $('[data-toggle="tooltip"]').tooltip()
    })
    </script>

app/views/quiz_creation/update.html.erb
<h1>QuizCreation#update</h1>
<p>Find me in app/views/quiz_creation/update.html.erb</p>