config/routes.rb
Rails.application.routes.draw do
  root to: 'quiz_creation#index'
  devise_for :quiz_users, controllers: { registrations: "quiz_users/registrations", confirmations: "quiz_users/confirmations", sessions:"quiz_users/sessions" }

  resources :quiz_creation do
    collection do
      get :tutorials
      get :rejected_quizzes
      get :approved_quizzes
      get :submitted_quizzes
      get :unfinished_quizzes
    end
  end
  devise_scope :quiz_user do
    match 'login'            => 'quiz_users/sessions#create',         :via => :post
    match 'signup'           => 'quiz_users/registrations#create',    :via => :post
  end
  resources :courses
  resources :labels

  resources :quizzes do
    member do
      get :approve
      get :reject
      get :new_verison
      get :submit_for_approval
      get :study_guide
    end
    collection do
      get :quiz_results
    end
    resources :questions, :except => [:index] do
      member do
        put :change_order
      end
    end
  end

  get '/quiz_user_account', to: 'quiz_creation#quiz_user_account'
  post '/settings', to: 'quiz_creation#settings'
  post '/check_email', to: 'quiz_creation#check_email'
  post '/set_comment', to: 'quizzes#set_comment'
  post '/set_question_comment', to: 'questions#set_question_comment'
  post '/switch_alerts', to: 'quiz_creation#switch_alerts'
  get '/messages', to: 'quiz_creation#messages'

  

  post '/set_sample_question', to: 'quiz_creation#set_sample_question'
  match '*path' => redirect('/'), via: :get
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_quiz_user!
  
  def index
    data_params = {}
    res_json = make_request("api/v1/labels",data_params,"GET")
    if res_json['success']
      @labels = res_json['labels']
    else
      flash[:alert] = "An error occured while displaying labels"
      redirect_to :back
    end
  end
  
  def new
  end

  def create
    error_msgs = []
    data_params={}
    data_params[:label] = params[:label]
    res_json = make_request("api/v1/labels",data_params,"POST")
    if res_json['success']
      label_id = res_json['label']['id']
      redirect_to label_path(label_id) and return
    else
      flash[:alert] = "An error occured while adding label"
      redirect_to :back
    end
  end

  def show
    data_params={}
    res_json = make_request("api/v1/labels/#{params[:id]}",data_params,"GET")
    if res_json['success']
      @label = res_json['label']
    else
      flash[:alert] = res_json["message"]
      redirect_to root_path
    end

  end

  def edit
    data_params={}
    res_json = make_request("api/v1/labels/#{params[:id]}/edit",data_params,"GET")

    if res_json['success']
      @label = res_json['label']
    else
      flash[:alert] = res_json["message"]
      redirect_to root_path
    end
  end

  def update
    data_params = {}
    data_params[:label] = params[:label]
    res_json = make_request("api/v1/labels/#{params[:id]}",data_params,"PUT")
    if res_json['success']
      label_id = res_json['label']['id']
      flash[:success] = "label updated successfully"
      redirect_to label_path(label_id)
      return
    else
      redirect_to :back
    end
  end
  

  def destroy
    data_params ={}
    res_json = make_request("api/v1/labels/#{params[:id]}",data_params,"DELETE")
    if res_json['success']
      flash[:success] = "label deleted successfully"
    else
      flash[:error] = "Could not delete label for some reason, Try again later."
    end
    redirect_to labels_path
  end

  private

    def label_params
      params.require(:label).permit(:id,:name)
    end
end

app/views/labels/_edit_form.html.erb
<%= form_tag({action: 'update'},{multipart: true, :method => "patch", :class => 'form-horizontal bordered-group label-new-form'}) do %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Label Name</label>
    </div>
    <div class="col-sm-4">
      <%= text_field_tag "label[name]", "#{@label['name']}", class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">
      <%= submit_tag "Update Label", class: 'btn btn-primary'  %>
      <%= link_to 'Cancel', label_path(@label['id']), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {

  $(".label-new-form").validate({

    rules: {
      "label[name]": {
        required: true
      }
    },
    messages: {
      "label[name]": {
        required: "Label Name cannot be blank"
      }
    },
    submitHandler: function(form) {
      form.submit();
    }
  });
});
</script>

app/views/labels/_form.html.erb
<%= form_tag(labels_path, {multipart: true, :class => 'form-horizontal bordered-group label-new-form'}) do %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Label Name</label>
    </div>
    <div class="col-sm-4">
      <%= text_field_tag "label[name]", '',class: 'form-control'%>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-xs-6">
      <%= submit_tag "Create Label", class: 'btn btn-primary'  %>
      <%= link_to 'Cancel', '/', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {

  $(".label-new-form").validate({

    rules: {
      "label[name]": {
        required: true
      }
    },
    messages: {
      "label[name]": {
        required: "Label Name cannot be blank"
      }
    },
    submitHandler: function(form) {
      form.submit();
    }
  });
});
</script>

app/views/labels/edit.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>Edit <%= @label['name'] %></h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'edit_form', cancel_link: label_path(@label['id']) %>
      </div>
    </div>
  </div>
</div>

app/views/labels/index.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <div class="col-sm-7">
      <h1>All Labels</h1>
    </div>
    <div style="float: right;">
      <%= link_to "Add New Label",new_label_path %>
    </div>
  </div>
  <div class="panel-body">
     <div class="row no-margin">
        <table class="table table-responsive table-hover" id="table_body_unfinished">
          <tr>
            <th>#</th>
            <th>Label Name</th>
            <th>Edit</th>
            <th>Delete</th>
            <th>View Label</th>
          </tr>
          <% @labels.each_with_index do |label, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= label['name'] %></td>
              <td>
                <%= link_to 'Edit Label',edit_label_path(label['id']), :class => 'btn btn-default' %>
              </td>
              <td>
                <%= link_to "Delete Label", "/labels/#{label['id']}", :method => :delete, :data => {:confirm => 'Are you sure you want to delete this label?'}, :class => 'btn btn-danger' %>
              </td>
              <td>
                <%= link_to 'View Label',label_path(label['id']), :class => 'btn btn-default' %>
              </td>
            </tr>
          <% end %>
        </table>
     </div>
  </div>
</div>

app/views/labels/new.html.erb
<div class="panel mb25">
  <div class="panel-heading broder">
    <h1>Add New Label</h1>
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'form', :cancel_link => quiz_creation_index_path %>
      </div>
    </div>
  </div>
</div>

app/views/labels/show.html.erb
<ol class="breadcrumb">
  <li>
    <a href="/">Home</a>
  </li>
  <li>
    <a href="/labels">Labels</a>
  </li>
  <li class="active">
    <%= @label['name'] %>
  </li>
</ol>

<div class="panel mb25">
  <div class="panel-body" id="uniq-panel">
    <div class="col-md-12">
      <div>
        <b>Label Name:</b>
        <%= @label['name'] %>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript">
  
</script>

app/views/labels/show.js.erb
$("#chatBox").empty();
$("#chatBox").html("<%= escape_javascript(render(partial: 'quizzes/chat_box', :locals => {:@chats => @chats})) %>");